---
- name: install spotify through flatpak
  become: true
  community.general.flatpak:
    remote: flathub
    name: com.spotify.Client

- name: install xournal++ through flatpak
  become: true
  community.general.flatpak:
    remote: flathub
    name: com.github.xournalpp.xournalpp

- name: install Moonlight through flatpak
  become: true
  community.general.flatpak:
    remote: flathub
    name: com.moonlight_stream.Moonlight

- name: install VLC media player
  become: true
  package:
    name: vlc
    state: present

- name: install Steam destktop
  become: true
  package:
    name: steam
    state: present

- name: install kdeconnect
  become: true
  package:
    name: kde-connect
    state: present

- name: install actual budget through flatpak
  become: true
  community.general.flatpak:
    remote: flathub
    name: com.actualbudget.actual

- name: install libreoffice suite
  become: true
  package:
    name: libreoffice
    state: present

- name: add copr repo for signal
  become: true
  community.general.copr:
    name: useidel/signal-desktop
    state: enabled

- name: install signal desktop
  become: true
  package:
    name: signal-desktop
    state: present

- name: add copr repositories for joplin
  become: true
  community.general.copr:
    name: taw/joplin
    state: enabled

- name: install joplin
  become: true
  package:
    name: joplin
    state: present
