---
- name: install gnome shell extensions
  become: true
  package:
    name:
      - gnome-shell-extension-caffeine
      - gnome-shell-extension-dash-to-dock
    state: present

- name: prefer dark theme
  community.general.dconf:
    key: "/org/gnome/desktop/interface/color-scheme"
    value: "'prefer-dark'"
